GET  http://localhost:4000/login
Content-Type: application/json

{
    "username": "anubhab.mukherjee2013@gmail.com"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYW51YmhhYi5tdWtoZXJqZWUyMDEzQGdtYWlsLmNvbSIsImlhdCI6MTU3OTUxNjcyM30.vwd-66qCXuiAvWB2a1YIKy3d2oohhI98YBOv4900Xbk"
}

###
DELETE  http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYW51YmhhYi5tdWtoZXJqZWUyMDEzQGdtYWlsLmNvbSIsImlhdCI6MTU3OTUxNjcyM30.vwd-66qCXuiAvWB2a1YIKy3d2oohhI98YBOv4900Xbk"
}